### ISSUE TITLE
Variable KV size support

### ISSUE THREAD

**Issue by hoaaosnw** [dmemsys/Anole#3]
Does Anole support variable KV size? It seems in `alloc` and `free`, Anole manages memory at `block_size_` granularity, which is fixed during initialization. And also, in `rdma_read_sid_sync`, Anole read `block_size_` instead of `kv_size`. It seems if Anole support variable KV size, it would add a lot complexity than existing implementation.

**Comment by bernardshen** [comment]
Thank you for your comment. The current implementation of Anole only supports fixed-sized KVs. The design of Anole focuses on efficiently executing caching algorithms on DM. Supporting KV of variable sizes is orthogonal to the design of Anole.
